#!/usr/bin/env python

from itertools import batched
import re
from pathlib import Path

spaces = re.compile(r"(\s+)")

try:
    while line := input():
        for field, sep in batched(spaces.split(line)+[""], 2):
            if field.count("/") > 3:
                print(Path(field).name, end=sep)
            else:
                print(field, end=sep)
        print()
except (EOFError, KeyboardInterrupt, BrokenPipeError):
    pass
