from typing import Protocol


class Console(Protocol):
    def close(self, reason: str) -> None: ...
    async def input(self, prompt: str = "") -> str: ...
    async def print(self, *strs: str, sep: str = " ", end: str = "\n") -> None: ...
