name: "Run tests"

on: [push]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read

jobs:
    test:
        runs-on: "ubuntu-latest"

        steps:
            - name: "GitHub: Checkout Repository"
              uses: "actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8" #v5.0.0
              with:
                  submodules: true

            - name: "GitHub: Setup Nix"
              # IMPORTANT:
              # Consider GitHub Actions Pinning for additional security.
              # See: https://stackoverflow.com/a/78905195
              uses: "aldoborrero/use-nix-action@3fa3bdff0a49c05518619f76d69f38da05d29cf2" # v5
              with:
                # NOTE:
                # Set 'nix_path' by:
                #  - Picking a channel → https://status.nixos.org/
                #  - Pin 'nixpkgs' → https://nix.dev/reference/pinning-nixpkgs
                nix_path: nixpkgs=channel:nixos-unstable
                use_nix_profile: true

            - name: "Nix: Build"
              run: |
                nix develop -c bash -c cmake --workflow test
